### ISSUE TITLE
OSError: bubble//grid.txt not found.

### ISSUE THREAD

**Issue by MadMMan** [tinarwhite/2020_AIAA_Scitech#1]
While I was trying to run the results_bubble_cluster from 2020_AIAA_Scitech, the following error is coming.
 

  File "/home/user_name/anaconda3/envs/tensorflow/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)

OSError: bubble//grid.txt not found.

@tinarwhite , Can you help me why it is giving this error as you are the author of this work?

**Comment by tinarwhite** [comment]
Did you download the input data files here, and are you running the script from a location where it can find the files?
https://github.com/tinarwhite/2020_AIAA_Scitech/tree/master/bubble

**Comment by MadMMan** [comment]
There were two problems while I was running the script. 
1. numpy was not taking file while it is in sub-directory. So Simply I put the file in current working directory.
2. As I am executing the script in Linux OS, I had to give permission "ALLOW THIS FILE TO RUN AS A PROGRAM".
All Done.

BTW thank you for replying back.
